### ISSUE TITLE
projfeat3d

### ISSUE THREAD

**Issue by meteorshowers** [gengshan-y/high-res-stereo#16]
why use projfeat3d function?
it seems no different to 3d conv on function.

**Comment by gengshan-y** [comment]
I think you are right. At the time of writing this piece of code, I found (or thought) conv2d was better-optimized in speed than conv3d in pytorch.

**Comment by meteorshowers** [comment]
there will be some different between
 the projfeat3d and 3d function mainly on the h*w channel
1234
5678

12345678

projfeat3d will consider 45position, which is not a neighbor in spatial.
what do you think about it?

**Comment by gengshan-y** [comment]
If we are talking about 2D convolutions with 1x1 kernel size (in the projfeat3d) vs 3D convs with 1x1x1 kernel, no neighbor is considered. In this case they are equivalent. Does that make sense?

**Comment by meteorshowers** [comment]
It seems only aggregation information on C channels.
yes, it makes sense.
I am discouraged that the calculation of cnn based stereo is too high which can not be applyed into 
real world.
the  small cnn model's performace is not as well as sgbm(10 ms).
What's your opinion？

**Comment by gengshan-y** [comment]
It depends. Generalization ability is definitely a desired feature of deep stereo methods, which seems to be lacking in many current methods, compared to traditional ones. Compute is a tricker issue in my opinion, since it depends on the hardware architecture and it is not easy to say some method is fast enough without mentioning the application.

**Comment by meteorshowers** [comment]
Thanks for your reply.
