### ISSUE TITLE
high-res encoder feature to deal with thin structures

### ISSUE THREAD

**Issue by oliverxudd** [gengshan-y/high-res-stereo#31]
Hi gengshan, in your paper, "coarse-to-fine methods struggle to match **thin structures that “disappear” at coarse resolutions** [3]. In- stead, our model computes a high-res encoder feature". 
But encoder inside HSM gives cost volume of 1/8 original resolution so it is not really high-res feature, right? So how does HSM overcome problem of thin structures disappearing at coarse resolutions?

**Comment by gengshan-y** [comment]
Hi, HSM does not use full-res feature map to build a full-res cost volume, which is too expensive for 4K images. 
We address the thin structure disappearing issue in coarse-to-fine estimation in two ways,
(1) "coarse-resolution image" vs "coarse-resolution feature map" extracted from a full-res image. In HSM, we use the latter because the high-res information could be kept in a relative low-res, but high-dimension feature map. 
(2) "delta cost volume"  vs "full cost volume" by . We use the later and always search for correspondences in the full range. This avoids mistakes in the coarse-resolution being propagated to the fine-resolution.
