### ISSUE TITLE
Reason for a very good accuracy

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [gengshan-y/high-res-stereo#39]
Hi,

What is the reason that highres-stereo achieves very good accuracy as compared to PSMNet or GANet and that too with much lesser number of layers and hence lesser compute requirements? Is there some basic logical step that is missing in the other two?

**Comment by gengshan-y** [comment]
Hi, it's hard to say what is missing from PSMNet and GANet since both already achieves great performance on KITTI. 
The major difference in terms of design principle is that we target on high-res. There are several design principles of learning stereo matching on high-res images listed at the beginning of Sec 3. 

I'd say besides the coarse-to-fine model design, high-res data and the augmentation tricks are also important factors.

**Comment by Diksha-Moolchandani** [comment]
thanks
